### ISSUE TITLE
Proposal: add dynamic inventory 

### ISSUE THREAD

**Issue by bbl** [maxkrivich/aws-terraform-ansible-docker-elk-python#1]
There's a possible improvement that will eliminate manual editing of the inventory ([hosts.yaml](https://github.com/maxkrivich/aws-terraform-ansible-docker-elk-python/blob/master/infra/ansible/hosts.yml)) file.
Ansible [dynamic inventory](https://docs.ansible.com/ansible/latest/user_guide/intro_dynamic_inventory.html) might be used instead.
E.g.:
- https://github.com/nbering/terraform-inventory
- https://github.com/adammck/terraform-inventory

**Comment by maxkrivich** [comment]
@bbl thanks for your comment! 😄

**Comment by maxkrivich** [comment]
Thanks for hint one more time(043b52b5c133c26bc5700e44c207baf6fa350c9f), I'll close the issue.
